name: CI
on:
  push:
    branches:
      - main
      - comp/**
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  buildAndTest:
    runs-on: ubuntu-24.04
    container: ros:jazzy
    steps:
      - uses: actions/checkout@v2
        with:
          path: src/ateam_software
          submodules: true
      - name: Install Dependencies
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          sudo apt-get update
          rosdep update --rosdistro=jazzy
          rosdep install --from-paths . --ignore-src -y
      - name: Build
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build
      - name: Test
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon test
          colcon test-result --verbose 
